-- Copyright (C) 2015 Hans Giebenrath
-- 
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
-- 
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
-- 
-- You should have received a copy of the GNU General Public License
-- along with this program.  If not, see <http://www.gnu.org/licenses/>

-- delete group: delete gallery_broker, images should be deleted in application layer (place images on filesystem in directory named <group_id> -> deletin pretty easy
-- delete gallery: delete permission_broker (place images in firectory named <group_id>/<gallery_id> 
-- delete user: delete all images from that user (done by deleting all images from its character), delete permission_broker
-- delete character: delete all images from that character, delete gallery, delete permission_broker
-- delete image: delete permission_broker
